/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;


import com.mysql.cj.protocol.Resultset;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.lang.String;

public class AdminDashboard extends javax.swing.JFrame {

    
    public AdminDashboard() {
        initComponents();
        Count_Student();
        Count_lecturer();
        CountDepITstu();
        CountDepBusinessstu();
        Count_bus_Lect();
        Count_IT_Lect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCansel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        CountStu = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        lblLecCount = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblManageStu = new javax.swing.JLabel();
        lblManageLec = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        lblCountBusStu = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lblCountITstu = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        lblCountBusLec = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        lblCountITlec = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-menu-48White.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 6, -1, 40));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 64, -1, -1));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-male-user-30.png"))); // NOI18N
        jLabel2.setText("Welcome, Admin");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 10, -1, -1));

        btnCansel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCansel.setForeground(new java.awt.Color(255, 255, 255));
        btnCansel.setText("X");
        btnCansel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCansel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCanselMouseClicked(evt);
            }
        });
        jPanel1.add(btnCansel, new org.netbeans.lib.awtextra.AbsoluteConstraints(919, 6, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("University Management System");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 14, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 50));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CountStu.setFont(new java.awt.Font("Segoe UI Historic", 1, 32)); // NOI18N
        CountStu.setForeground(new java.awt.Color(102, 102, 102));
        CountStu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/students-50.png"))); // NOI18N
        jPanel10.add(CountStu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jPanel8.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 194, 112));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("No Of Student");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("No Of Lecturer");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, -1, -1));

        jPanel15.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(102, 102, 255)));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLecCount.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblLecCount.setForeground(new java.awt.Color(102, 102, 102));
        lblLecCount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lecture (1)-50.png"))); // NOI18N
        jPanel15.add(lblLecCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jPanel8.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 194, 118));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 51, 51));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-26.png"))); // NOI18N
        jLabel4.setText("  Home Page");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, 260, -1));

        lblManageStu.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblManageStu.setForeground(new java.awt.Color(153, 153, 153));
        lblManageStu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-student-registration-30.png"))); // NOI18N
        lblManageStu.setText(" Manage Student");
        lblManageStu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblManageStu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageStuMouseClicked(evt);
            }
        });
        jPanel2.add(lblManageStu, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 174, -1, -1));

        lblManageLec.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblManageLec.setForeground(new java.awt.Color(153, 153, 153));
        lblManageLec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-teacher-30 (2).png"))); // NOI18N
        lblManageLec.setText(" Manage Lecturer");
        lblManageLec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblManageLec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageLecMouseClicked(evt);
            }
        });
        jPanel2.add(lblManageLec, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 256, -1, -1));

        jPanel7.setBackground(new java.awt.Color(153, 0, 153));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-exit-26.png"))); // NOI18N
        jLabel5.setText("  Log Out");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 356, 260, -1));

        jPanel8.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 520));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("IT Department ");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Business Department");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, -1, -1));

        jPanel12.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 255, 0)));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCountBusStu.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jPanel12.add(lblCountBusStu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 20, -1));

        jPanel8.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 60, 80));

        jPanel11.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 255, 0)));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCountITstu.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jPanel11.add(lblCountITstu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 20, 30));

        jPanel8.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 60, 80));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Business Department");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, -1, -1));

        jPanel13.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 153, 153)));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCountBusLec.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jPanel13.add(lblCountBusLec, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jPanel8.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 430, 60, 80));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("IT Department");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, -1, -1));

        jPanel14.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 153, 153)));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCountITlec.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jPanel14.add(lblCountITlec, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 20, -1));

        jPanel8.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 60, 80));

        jPanel5.setBackground(new java.awt.Color(0, 255, 0));
        jPanel5.setForeground(new java.awt.Color(0, 204, 153));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 4, 140));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/20221008_090521.jpg"))); // NOI18N
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 570));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCanselMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCanselMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCanselMouseClicked

    private void lblManageStuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageStuMouseClicked
        StudentD manageStudent = new StudentD();
        manageStudent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblManageStuMouseClicked

    private void lblManageLecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageLecMouseClicked
        ManageLecturer manageLecturer = new ManageLecturer();
        manageLecturer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblManageLecMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        SelectType selectType = new SelectType();
        selectType.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    public void CountDepITstu(){
            try{
           
    
             Connection con = DBConnection.getConnection();
             PreparedStatement pst = con.prepareStatement("Select COUNT(*) from studentdetails where Department = ? ");
             pst.setString(1, "School of Computing");
             ResultSet rs = pst.executeQuery();
             while(rs.next()){
               int count = rs.getInt(1);
          
                lblCountITstu.setText(String.valueOf(count));
            }
       }
       catch(Exception e){
           e.printStackTrace();
        }
    }
       public void CountDepBusinessstu(){
            try{
           
    
             Connection con = DBConnection.getConnection();
             PreparedStatement pst = con.prepareStatement("Select COUNT(*) from studentdetails where Department = ? ");
             pst.setString(1, "School of Business");
             ResultSet rs = pst.executeQuery();
             while(rs.next()){
               int count = rs.getInt(1);
          
                lblCountBusStu.setText(String.valueOf(count));
            }
       }
       catch(Exception e){
           e.printStackTrace();
        }
    }
    
    
    public void Count_Student(){
        
       try{
           
    
             Connection con = DBConnection.getConnection();
             PreparedStatement pst = con.prepareStatement("Select COUNT(*) from studentdetails");
             ResultSet rs = pst.executeQuery();
             while(rs.next()){
               int count = rs.getInt(1);
          
                CountStu.setText(String.valueOf(count));
            }
       }
       catch(Exception e){
           e.printStackTrace();
        }
    }
    
    
   public void Count_IT_Lect(){
        try {
           Connection con = DBConnection.getConnection();
           PreparedStatement ps = con.prepareStatement("Select COUNT(*) from managelecturer where Department = ?");
           ps.setString(1, "School of Computing");
           ResultSet rss = ps.executeQuery();
           while(rss.next()){
               int countLec = rss.getInt(1);
               
               lblCountITlec.setText(String.valueOf(countLec));
           }
        } 
        catch (Exception e) {
            e.printStackTrace();
        }
    }
   
    public void Count_bus_Lect(){
        try {
           Connection con = DBConnection.getConnection();
           PreparedStatement ps = con.prepareStatement("Select COUNT(*) from managelecturer where Department = ?");
           ps.setString(1, "School of Business");
           ResultSet rss = ps.executeQuery();
           while(rss.next()){
               int countLec = rss.getInt(1);
               
               lblCountBusLec.setText(String.valueOf(countLec));
           }
        } 
        catch (Exception e) {
            e.printStackTrace();
        }
    }
   
    
    public void Count_lecturer(){
        try {
           Connection con = DBConnection.getConnection();
           PreparedStatement ps = con.prepareStatement("Select COUNT(*) from managelecturer");
           ResultSet rss = ps.executeQuery();
           while(rss.next()){
               int countLec = rss.getInt(1);
               
               lblLecCount.setText(String.valueOf(countLec));
           }
        } 
        catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CountStu;
    private javax.swing.JLabel btnCansel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblCountBusLec;
    private javax.swing.JLabel lblCountBusStu;
    private javax.swing.JLabel lblCountITlec;
    private javax.swing.JLabel lblCountITstu;
    private javax.swing.JLabel lblLecCount;
    private javax.swing.JLabel lblManageLec;
    private javax.swing.JLabel lblManageStu;
    // End of variables declaration//GEN-END:variables
}
