/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mahel
 */
public class LoadingPage extends javax.swing.JFrame {

    /**
     * Creates new form LoadingPage
     */
    public LoadingPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();
        lblTitle = new javax.swing.JLabel();
        lblPresntage = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/building-place-university-png-200.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 200, 200));

        ProgressBar.setBackground(new java.awt.Color(204, 204, 204));
        ProgressBar.setForeground(new java.awt.Color(255, 153, 51));
        jPanel2.add(ProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 324, 620, 10));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 153));
        lblTitle.setText("University Managment System");
        jPanel2.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        lblPresntage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPresntage.setForeground(new java.awt.Color(255, 255, 255));
        lblPresntage.setText("0 %");
        jPanel2.add(lblPresntage, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Loading .......");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/20221006_190916.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        LoadingPage lp = new LoadingPage();
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                lp.setVisible(true);
            }
        });
        
        SelectType st = new SelectType();
        try {
             for(int i=0; i<=100; i++){
           
                Thread.sleep(80);
                lp.ProgressBar.setValue(i);
                lp.lblPresntage.setText(String.valueOf(i)+ "%");
                if(i==100){
                  lp.setVisible(false);
                  lp.dispose();
                }
            
              }
            } catch (InterruptedException ex) {
                Logger.getLogger(LoadingPage.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            st.setVisible(true);
            lp.dispose();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblPresntage;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
