/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

/**
 *
 * @author mahel
 */
public class SelectType extends javax.swing.JFrame {

    /**
     * Creates new form SelectType
     */
    public SelectType() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblCansel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblLecturer = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblStudent = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 102));
        jLabel1.setText("University Managment System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("WELCOME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCansel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCansel.setForeground(new java.awt.Color(255, 255, 255));
        lblCansel.setText("X");
        lblCansel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCansel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCanselMouseClicked(evt);
            }
        });
        jPanel1.add(lblCansel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 153));
        jLabel4.setText("Select Account");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-admin-settings-male-64.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        lblAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAdmin.setForeground(new java.awt.Color(204, 255, 204));
        lblAdmin.setText("Admin");
        lblAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAdminMouseClicked(evt);
            }
        });
        jPanel1.add(lblAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 56, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-teacher-68.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        lblLecturer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLecturer.setForeground(new java.awt.Color(204, 255, 204));
        lblLecturer.setText("Lecturer");
        lblLecturer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLecturer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLecturerMouseClicked(evt);
            }
        });
        jPanel1.add(lblLecturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-student-male-64.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        lblStudent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblStudent.setForeground(new java.awt.Color(204, 255, 204));
        lblStudent.setText("Student");
        lblStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStudentMouseClicked(evt);
            }
        });
        jPanel1.add(lblStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 153, 102));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 170, 5));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 310, 530));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/20221008_090521.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStudentMouseClicked
        StudentLoginPage studentLoginPage = new StudentLoginPage();
        studentLoginPage.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_lblStudentMouseClicked

    private void lblLecturerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLecturerMouseClicked
        LecturerLoginPage lecturerLoginPage = new LecturerLoginPage();
        lecturerLoginPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblLecturerMouseClicked

    private void lblAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdminMouseClicked
        AdminLPage adminLPage = new AdminLPage();
        adminLPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblAdminMouseClicked

    private void lblCanselMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCanselMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCanselMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectType().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblCansel;
    private javax.swing.JLabel lblLecturer;
    private javax.swing.JLabel lblStudent;
    // End of variables declaration//GEN-END:variables
}
