/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import java.sql.PreparedStatement;
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRPrintXmlLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author mahel
 */
public class StudentDetailsView extends javax.swing.JFrame {

    /**
     * Creates new form StudentDetailsView
     */
    public StudentDetailsView() {
        initComponents();
    }

    Connection con = (Connection)DBConnection.getConnection();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblCansel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DisplayStudentData = new rojeru_san.complementos.RSTableMetro();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        CbGetBatch = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        SearchUsingProgramme = new rojerusan.RSComboMetro();
        jLabel21 = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        btnPrint = new rojerusan.RSButtonMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCansel.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        lblCansel.setForeground(new java.awt.Color(153, 51, 255));
        lblCansel.setText("X");
        lblCansel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCansel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCanselMouseClicked(evt);
            }
        });
        jPanel2.add(lblCansel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 10, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        DisplayStudentData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Index No", "Name", "Address", "Age", "Email", "Batch", "Programme", "Contact"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        DisplayStudentData.setColorBackgoundHead(new java.awt.Color(102, 102, 255));
        DisplayStudentData.setColorBordeFilas(new java.awt.Color(153, 153, 153));
        DisplayStudentData.setColorBordeHead(new java.awt.Color(153, 153, 153));
        DisplayStudentData.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        DisplayStudentData.setColorSelBackgound(new java.awt.Color(255, 51, 51));
        DisplayStudentData.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        DisplayStudentData.setFuenteFilas(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DisplayStudentData.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DisplayStudentData.setFuenteHead(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DisplayStudentData.setGridColor(new java.awt.Color(255, 255, 255));
        DisplayStudentData.setRowHeight(40);
        DisplayStudentData.setSelectionBackground(new java.awt.Color(255, 255, 255));
        DisplayStudentData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DisplayStudentDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DisplayStudentData);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 1140, 330));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 51));
        jLabel1.setText("Students Details\n");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 180, -1));

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 230, 5));

        CbGetBatch.setBackground(new java.awt.Color(153, 153, 255));
        CbGetBatch.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        CbGetBatch.setForeground(new java.awt.Color(255, 255, 255));
        CbGetBatch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Student Department", "School of Business", "School of Computing" }));
        CbGetBatch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        CbGetBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbGetBatchActionPerformed(evt);
            }
        });
        jPanel2.add(CbGetBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 510, 40));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-certificate_color-48.png"))); // NOI18N
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 50, 60));

        SearchUsingProgramme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchUsingProgrammeActionPerformed(evt);
            }
        });
        jPanel2.add(SearchUsingProgramme, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 360, 40));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-library-48.png"))); // NOI18N
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 60, 60));

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left-chevron-30.png"))); // NOI18N
        lblBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        jPanel2.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnPrint.setBackground(new java.awt.Color(255, 102, 153));
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 640, 120, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCanselMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCanselMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCanselMouseClicked

    private void DisplayStudentDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisplayStudentDataMouseClicked
        
    }//GEN-LAST:event_DisplayStudentDataMouseClicked

    private void CbGetBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbGetBatchActionPerformed
        if(CbGetBatch.getSelectedItem().equals("School of Business")){
            SearchUsingProgramme.removeAllItems();
            SearchUsingProgramme.setSelectedItem(null);
            SearchUsingProgramme.addItem("Select Programme");
            SearchUsingProgramme.addItem("Event Managment");
            SearchUsingProgramme.addItem("Digital Marketing");
        }
        if(CbGetBatch.getSelectedItem().equals("School of Computing")){
            SearchUsingProgramme.removeAllItems();
            SearchUsingProgramme.setSelectedItem(null);
            SearchUsingProgramme.addItem("Select Programme");
            SearchUsingProgramme.addItem("Computer System Design");
            SearchUsingProgramme.addItem("Software Engineering");
        }

        else if(CbGetBatch.getSelectedItem().equals("Select Student Department")){
            SearchUsingProgramme.removeAllItems();
        }

        Search();

    }//GEN-LAST:event_CbGetBatchActionPerformed

    private void SearchUsingProgrammeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchUsingProgrammeActionPerformed
        try {
            Search();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_SearchUsingProgrammeActionPerformed

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        LecturerDashboard ld = new LecturerDashboard();
        ld.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBackMouseClicked

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        try {
            String getpro = SearchUsingProgramme.getSelectedItem().toString();
            
            JasperDesign jdesign = JRXmlLoader.load("D:\\JavaNetBeans\\UniManagment\\src\\Forms\\studentReport.jrxml");
            String sql = "Select * from studentdetails where programme = '"+getpro+"'";
            
            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText(sql);
            
            jdesign.setQuery(updateQuery);
            
            JasperReport jreport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jprint = JasperFillManager.fillReport(jreport,null,con);
            
            JasperViewer.viewReport(jprint);
            
            } 
        catch (JRException ex) {
            Logger.getLogger(StudentDetailsView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

      public void Search(){
        try {
          
        int getdep = CbGetBatch.getSelectedIndex();
        int c;
        String programme = null ;
      
        if(getdep == 1 ){
            if(SearchUsingProgramme.getSelectedIndex() == 1){
               programme = "Event Managment";
            }
            else if(SearchUsingProgramme.getSelectedIndex() == 2){
               programme = "Digital Marketing";
            }
            else if(SearchUsingProgramme.getSelectedIndex() == 3){
               programme = "Digital Banking and Finance";
        }
            
        }
        else if(getdep == 2){
           if(SearchUsingProgramme.getSelectedIndex() == 1){
               programme = "Computer System Design";
            }
            else if(SearchUsingProgramme.getSelectedIndex() == 2){
              programme = "Software Engineering";
        }     
       }
        
        
         String quary = "Select * from studentdetails where Programme = ?";          
         java.sql.PreparedStatement preparedStatement = con.prepareStatement(quary);
         preparedStatement.setString(1, programme);
         ResultSet rs = preparedStatement.executeQuery();

         ResultSetMetaData Rss = (ResultSetMetaData) rs.getMetaData();
         c = Rss.getColumnCount();
         
         DefaultTableModel Df = (DefaultTableModel)DisplayStudentData.getModel();
         Df.setRowCount(0);
         
         while(rs.next())
         {
           Vector v2 = new Vector();
           
           for(int a=1; a<=c; a++){
               v2.add(rs.getString("IndexNo"));
               v2.add(rs.getString("Name"));
               v2.add(rs.getInt("Age"));
               v2.add(rs.getString("Address"));
               v2.add(rs.getString("Email"));
               v2.add(rs.getString("Department"));
               v2.add(rs.getString("Programme"));
               v2.add(rs.getInt("Phone"));
           }
           
           Df.addRow(v2);
             
         }
      
        } catch (Exception ex) {
            ex.printStackTrace();
        }    
        }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDetailsView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbGetBatch;
    private rojeru_san.complementos.RSTableMetro DisplayStudentData;
    private rojerusan.RSComboMetro SearchUsingProgramme;
    private rojerusan.RSButtonMetro btnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblCansel;
    // End of variables declaration//GEN-END:variables
}
