/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;



public class StudentLoginPage extends javax.swing.JFrame {


    
    Connection con =  (Connection) DBConnection.getConnection();
    
    public StudentLoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        DepSelect = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ProSelect = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        selectIndex = new javax.swing.JComboBox<>();
        btnSearch = new necesario.RSMaterialButtonCircle();
        lblCansel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("STUDENT");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signup-library-icon256.png"))); // NOI18N

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left-chevron-30.png"))); // NOI18N
        lblBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBack))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblBack)
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addComponent(jLabel2)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 560));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Programme");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        DepSelect.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DepSelect.setForeground(new java.awt.Color(255, 51, 51));
        DepSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select  Department", "School of Business", "School of Computing" }));
        DepSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepSelectActionPerformed(evt);
            }
        });
        jPanel2.add(DepSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 292, 37));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Department");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-library-50.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-certificate-50 (1).png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 54, 40));

        ProSelect.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ProSelect.setForeground(new java.awt.Color(255, 51, 51));
        ProSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProSelectActionPerformed(evt);
            }
        });
        jPanel2.add(ProSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 292, 37));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-identity-theft-50.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Index No");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 23)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 153));
        jLabel3.setText("View Exam Result");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        selectIndex.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectIndex.setForeground(new java.awt.Color(0, 0, 255));
        selectIndex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Index No" }));
        selectIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectIndexActionPerformed(evt);
            }
        });
        jPanel2.add(selectIndex, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 292, 37));

        btnSearch.setBackground(new java.awt.Color(153, 153, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 270, 58));

        lblCansel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCansel.setForeground(new java.awt.Color(255, 255, 255));
        lblCansel.setText("X");
        lblCansel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCansel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCanselMouseClicked(evt);
            }
        });
        jPanel2.add(lblCansel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 250, 5));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/20221008_111945.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 409, 548));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 410, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DepSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepSelectActionPerformed
        if(DepSelect.getSelectedItem().equals("School of Business")){
                selectIndex.removeAllItems();
                ProSelect.removeAllItems();
                ProSelect.setSelectedItem(null);
                ProSelect.addItem("Select Programme");
                ProSelect.addItem("Event Managment");
                ProSelect.addItem("Digital Marketing");
        }
        else if(DepSelect.getSelectedItem().equals("School of Computing")){
               selectIndex.removeAllItems();
               ProSelect.removeAllItems();
               ProSelect.setSelectedItem(null);
               ProSelect.addItem("Select Programme");
               ProSelect.addItem("Computer System Design");
               ProSelect.addItem("Software Engineering");
        }
        
        else if(DepSelect.getSelectedItem().equals("Select Student Department")){
               ProSelect.removeAllItems();
        }
    }//GEN-LAST:event_DepSelectActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if(DepSelect.getSelectedIndex() == 0){
             JOptionPane.showMessageDialog(this, "Select Department");
        }
        else if(ProSelect.getSelectedIndex() == 0){
             JOptionPane.showMessageDialog(this, "Select Programme");
        }
        else if(selectIndex.getSelectedIndex() == 0){
             JOptionPane.showMessageDialog(this, "Select Your Index Number");
        }
        else{
            String getIndex = selectIndex.getSelectedItem().toString();
            String depa = DepSelect.getSelectedItem().toString();
            String prog = ProSelect.getSelectedItem().toString();   
            
       try{
             java.sql.Connection con = DBConnection.getConnection();
             java.sql.PreparedStatement pst = con.prepareStatement("Select * from managestudentsresult where Department = ? and Programme = ? and IndexNo =? ");
             
             pst.setString(1, depa);
             pst.setString(2, prog);
             pst.setString(3, getIndex);
             
             ResultSet rs = pst.executeQuery();
             if(rs.next()){
                StudentResultView studentResultView = new StudentResultView((getIndex));
                studentResultView.setVisible(true);
                this.dispose();
             }
             else{
               JOptionPane.showMessageDialog(this, "Invalid ");
             }
         }
        catch(Exception e){
              e.printStackTrace();
         }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void lblCanselMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCanselMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCanselMouseClicked

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        SelectType selectType = new SelectType();
        selectType.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBackMouseClicked

    private void ProSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProSelectActionPerformed
         if (ProSelect.getSelectedIndex() == 1 || ProSelect.getSelectedIndex() == 2) {
               selectIndex.removeAllItems();
              
               displayIndexNo();
        }
      
    }//GEN-LAST:event_ProSelectActionPerformed

    private void selectIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectIndexActionPerformed
        
    }//GEN-LAST:event_selectIndexActionPerformed

    public void displayIndexNo(){ 
       try{
            String get_programme  = ProSelect.getSelectedItem().toString();
            selectIndex.removeAllItems();
            selectIndex.addItem("Select IndexNo");
            String sql = "Select * from managestudentsresult where Programme = ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, get_programme);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                selectIndex.addItem(rs.getString("IndexNo"));
            }
            
            }
            catch(Exception e){
               e.printStackTrace();
                
        }   
    }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentLoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DepSelect;
    private javax.swing.JComboBox<String> ProSelect;
    private necesario.RSMaterialButtonCircle btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblCansel;
    private javax.swing.JComboBox<String> selectIndex;
    // End of variables declaration//GEN-END:variables

    private Object studentResultView(String index) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
